### ISSUE TITLE
Create a keycloak deployment with persistent database for keycloak-ssi-deployment

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/keycloak-ssi-deployment#53]
- Define a reasonable configuration script to install keycloak on aws
- Add a potsgress database for the access by multiple instances
- Add a second instance for fault tolerance
- Reuse issuer keys so that issued wallet credentials can be held longer

**Comment by IngridPuppet** [comment]
I have a working solution when started with `./0.start-kc-oid4vci.sh`. 

However, should this wait for #70 ?

**Comment by nitch2019** [comment]
@IngridPuppet pls proceed with the ticket. There are no related to https://github.com/adorsys/keycloak-ssi-deployment/issues/70

**Comment by IngridPuppet** [comment]
Realized I've been missing (again) the points in the description. @Awambeng @forkimenjeckayang - May I have your input for each of these points? I'd like to have it discussed during a daily with Mr @francis-pouatcha.

More clarifications:
1. Define a reasonable configuration script to install keycloak on aws &rarr; Isn't this covered already?
2. Add a potsgress database for the access by multiple instances &rarr; Is the docker database reusable enough to satisfy this point?
3. Add a second instance for fault tolerance &rarr; Shouldn't this be handled on AWS?
4. Reuse issuer keys so that issued wallet credentials can be held longer &rarr;  Reusing keystore if file exists...

**Comment by forkimenjeckayang** [comment]
Hello Sir @IngridPuppet 
- For the first point, you're right, it has been covered. But the process was manual that's why we are now moving to creating an image to use for deploying our keycloak an AWS
- For the postgress database to handle multiple instances , that will be possible with an RDS on AWS. Where we have one RDS instance to contain databases for our applications.
- The third point ties with the second, having  a single RDS instance can help hold multiple databases which our application(s) can connect to.
- The last point i am not quite sure. Maybe Sir @francis-pouatcha cab help clarify

**Comment by francis-pouatcha** [comment]
> Reuse issuer keys so that issued wallet credentials can be held longer → Reusing keystore if file exists...
yes please. This is essential.

**Comment by nitch2019** [comment]
@forkimenjeckayang @Awambeng pls create the tickets for the points above

**Comment by IngridPuppet** [comment]
There is a pending PR linked to this issue:
- https://github.com/adorsys/keycloak-ssi-deployment/pull/78

**Comment by Awambeng** [comment]
The persistent database was resolved #79
