### ISSUE TITLE
kc deployment: Add information from our client (openid4vc-rest-api) to the deployment config

### ISSUE THREAD

**Issue by hugoib** [adorsys/keycloak-ssi-deployment#57]
Our PROD environment https://keycloak.solutions.adorsys.com has the client we use.

Our DEV environment https://keycloak-demo.solutions.adorsys.com doesn't. Add that config to the deployment config so we don't lose it when we upgrade.

**Comment by forkimenjeckayang** [comment]
The configuration of the openid4vc-rest-api client from the PROD enviroment has been exported , and now imported in the demo enviroment. Could be automated with this line of code....


![Image](https://github.com/user-attachments/assets/49178ff2-8bb6-4eaf-8615-c032f5cf9cc3)

But when the script is ran there's an error 


![Image](https://github.com/user-attachments/assets/39342d00-226c-4f80-9e70-7b14b3225a36)

Due to this file signing_service-test-credential.json. I believe it's caused  y recent changes
